In [1]:
import torch
import torchvision

## Torch Tensors

In [2]:
# This is a 1-D tensor
a = torch.tensor([2, 2, 1])
print(a)

tensor([2, 2, 1])


In [15]:
# This is a 2-D Tensor
b = torch.tensor([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(b)

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])


In [16]:
# This is a shape and size of tensor
print("a shape: {}, b shape: {}".format(a.shape, b.shape))
print("a size: {}, b size: {}".format(a.size(), b.size()))

a shape: torch.Size([3]), b shape: torch.Size([4, 3])
a size: torch.Size([3]), b size: torch.Size([4, 3])


In [8]:
# This is a float tensor
c = torch.FloatTensor([[1,2,3], [4,5,6]])
print(c)
c = torch.tensor([[1,2,3], [4,5,6]], dtype=torch.float)
print(c)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [9]:
# This is a double tensor
d = torch.DoubleTensor([1,2,3])
print(d)
d = torch.tensor([1,2,3], dtype=torch.double)
print(d)

tensor([1., 2., 3.], dtype=torch.float64)
tensor([1., 2., 3.], dtype=torch.float64)


In [11]:
# This is dtype of tensors
print("dtype of c: {}, dtype of d: {}".format(c.dtype, d.dtype))

dtype of c: torch.float32, dtype of d: torch.float64


In [12]:
# There are the mean and standard deviation of tensors
print("mean c: {}, mean d: {}".format(c.mean(), d.mean()))
print("std c: {}, std d: {}".format(c.std(), d.std()))

mean c: 3.5, mean d: 2.0
std c: 1.8708287477493286, std d: 1.0


### Reshape

In [22]:
# if one of the dimension is -1, its size can be inferred
print(b.view(-1,1))
print(b.view(12))
print(b.view(-1,4))
print(b.view(4,3))

tensor([[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12]])
tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])


In [23]:
b = b.view(1, -1)
print(b)
print(b.shape)

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])
torch.Size([1, 12])


### 3-D Tensor
(channels - rows - columns)

In [24]:
# This is 3-D Tensor with 2 channels, 3 rows, 4 columns
three_tensor = torch.randn(2, 3, 4)
print(three_tensor)
print(three_tensor.view(2, 12))
print(three_tensor.view(2, -1))

tensor([[[-1.1770,  1.0313, -0.4223,  0.3663],
         [ 0.8792,  0.9453,  0.9844,  0.9271],
         [ 0.0397,  0.9875,  0.6541,  0.9224]],

        [[ 0.0404,  0.5773,  0.5428, -1.4970],
         [-0.1100, -0.8215, -1.4823,  0.4505],
         [-0.6834,  0.8017,  1.2622,  0.6815]]])
tensor([[-1.1770,  1.0313, -0.4223,  0.3663,  0.8792,  0.9453,  0.9844,  0.9271,
          0.0397,  0.9875,  0.6541,  0.9224],
        [ 0.0404,  0.5773,  0.5428, -1.4970, -0.1100, -0.8215, -1.4823,  0.4505,
         -0.6834,  0.8017,  1.2622,  0.6815]])
tensor([[-1.1770,  1.0313, -0.4223,  0.3663,  0.8792,  0.9453,  0.9844,  0.9271,
          0.0397,  0.9875,  0.6541,  0.9224],
        [ 0.0404,  0.5773,  0.5428, -1.4970, -0.1100, -0.8215, -1.4823,  0.4505,
         -0.6834,  0.8017,  1.2622,  0.6815]])


### Matrix

In [25]:
# This is matrix with random numbers between 0 and 1
r = torch.rand(4,4)
r

tensor([[0.5195, 0.9510, 0.2776, 0.3511],
        [0.7656, 0.5406, 0.4647, 0.9470],
        [0.4584, 0.5397, 0.5138, 0.8047],
        [0.0048, 0.5370, 0.5054, 0.6994]])

In [26]:
# This is matrix with random numbers taken from normal distribution (mean = 0, variance = 1)
r2 = torch.randn(4,4)
print(r2)
print(r2.dtype)

tensor([[ 1.5113, -1.7348, -0.3191, -0.5814],
        [-0.6495,  0.2276,  0.5431, -0.2975],
        [-0.2255, -0.3163,  0.1784, -0.7139],
        [-0.6109, -0.5461,  0.4431, -0.9375]])
torch.float32


In [27]:
# This is array of 5 integers from values between 6 and 9 (exclusive of 10)
int_arr = torch.randint(6, 10, (5,))
int_arr

tensor([7, 6, 7, 7, 6])

In [28]:
# This is 2-D array integers
int_arr2 = torch.randint(6, 10, (3,3))
int_arr2

tensor([[6, 7, 8],
        [6, 6, 8],
        [7, 9, 6]])

In [29]:
# Get number of elements
print(torch.numel(int_arr))
print(torch.numel(int_arr2))

5
9


In [30]:
# This is matrix of zeros
zeros = torch.zeros(3, 3, dtype=torch.long)
# This is matrix of ones
ones = torch.ones(3, 3)
print(zeros)
print(zeros.dtype)
print(ones)
print(ones.dtype)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
torch.int64
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.float32


In [31]:
# Add two tensors, make sure they are same size and data type
add_results = torch.add(r, r2)
add_results

tensor([[ 2.0308, -0.7837, -0.0415, -0.2302],
        [ 0.1161,  0.7682,  1.0077,  0.6495],
        [ 0.2329,  0.2234,  0.6922,  0.0908],
        [-0.6061, -0.0091,  0.9485, -0.2381]])

In [32]:
# In-place addition => change value of r2
r2 == r2.add(r)

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

### Slicing

In [33]:
print(r2[:,1])
print(r2[:,:2])
print(r2[:3,:])

tensor([-1.7348,  0.2276, -0.3163, -0.5461])
tensor([[ 1.5113, -1.7348],
        [-0.6495,  0.2276],
        [-0.2255, -0.3163],
        [-0.6109, -0.5461]])
tensor([[ 1.5113, -1.7348, -0.3191, -0.5814],
        [-0.6495,  0.2276,  0.5431, -0.2975],
        [-0.2255, -0.3163,  0.1784, -0.7139]])


In [34]:
num_ten = r2[2,3]
print(num_ten)
print(num_ten.item())
print(r2[2,:])

tensor(-0.7139)
-0.713896632194519
tensor([-0.2255, -0.3163,  0.1784, -0.7139])
