In [1]:
import torch
import torchvision

## Torch Tensors

In [2]:
# This is a 1-D tensor
a = torch.tensor([2, 2, 1])
print(a)

tensor([2, 2, 1])


In [3]:
# This is a 2-D Tensor
b = torch.tensor([[1,2,3], [4,5,6], [7,8,9]])
print(b)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [4]:
# This is a shape and size of tensor
print("a shape: {}, b shape: {}".format(a.shape, b.shape))
print("a size: {}, b size: {}".format(a.size(), b.size()))

a shape: torch.Size([3]), b shape: torch.Size([3, 3])
a size: torch.Size([3]), b size: torch.Size([3, 3])


In [8]:
# This is a float tensor
c = torch.FloatTensor([[1,2,3], [4,5,6]])
print(c)
c = torch.tensor([[1,2,3], [4,5,6]], dtype=torch.float)
print(c)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [9]:
# This is a double tensor
d = torch.DoubleTensor([1,2,3])
print(d)
d = torch.tensor([1,2,3], dtype=torch.double)
print(d)

tensor([1., 2., 3.], dtype=torch.float64)
tensor([1., 2., 3.], dtype=torch.float64)


In [11]:
# This is dtype of tensors
print("dtype of c: {}, dtype of d: {}".format(c.dtype, d.dtype))

dtype of c: torch.float32, dtype of d: torch.float64


In [12]:
# There are the mean and standard deviation of tensors
print("mean c: {}, mean d: {}".format(c.mean(), d.mean()))
print("std c: {}, std d: {}".format(c.std(), d.std()))

mean c: 3.5, mean d: 2.0
std c: 1.8708287477493286, std d: 1.0
